// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EntityFramework;

namespace Repositories.EntityFramework.Migrations
{
    [DbContext(typeof(СustomerInquiryDbContext))]
    [Migration("20190206133831_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Currency", b =>
                {
                    b.Property<int>("CurrencyID");

                    b.Property<int>("CurrencyCode");

                    b.Property<string>("CurrencyName");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerContactEmail");

                    b.Property<string>("CustomerMobileNumer");

                    b.Property<string>("CustomerName");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Models.Status", b =>
                {
                    b.Property<int>("StatusID");

                    b.Property<int>("StatusCode");

                    b.Property<string>("StatusName");

                    b.HasKey("StatusID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyID");

                    b.Property<int?>("CustomerID");

                    b.Property<int>("StatusID");

                    b.Property<double>("TransactionAmount");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("TransactionID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Models.Currency", b =>
                {
                    b.HasOne("Models.Transaction", "Transaction")
                        .WithOne("Currency")
                        .HasForeignKey("Models.Currency", "CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Status", b =>
                {
                    b.HasOne("Models.Transaction", "Transaction")
                        .WithOne("Status")
                        .HasForeignKey("Models.Status", "StatusID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Transaction", b =>
                {
                    b.HasOne("Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerID");
                });
#pragma warning restore 612, 618
        }
    }
}
